In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("raw_data.csv")
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [3]:
df["tax"] = df["income"].apply(lambda x: 20 if x>= 50000 else 10)

In [4]:
df

    id          name   age country   gender   income  tax
0    1      John Doe  29.0     USA     Male  55000.0   20
1    1      John Doe  29.0     USA     Male  55000.0   20
2    2    Jane Smith   NaN  Canada   Female  62000.0   20
3    3          Alex   NaN     USA  Unknown  47000.0   10
4    4  Maria Garcia  34.0   Spain   Female      NaN   10
5    5        Li Wei  27.0   China     Male  51000.0   20
6    6           NaN  45.0   India   Female  73000.0   20
7    7    Ahmed Khan  38.0     NaN     Male  68000.0   20
8    8    Rachel Lee  29.0     USA   Female  62000.0   20
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0   10
10  10   Emily Davis  31.0     USA      NaN  58000.0   20

In [5]:
gender_map = {
    "Male":"M",
    "Female":"F",
    "Unknown":"M"
}

In [6]:
df["gender"] = df["gender"].map(gender_map)

In [7]:
df

    id          name   age country gender   income  tax
0    1      John Doe  29.0     USA      M  55000.0   20
1    1      John Doe  29.0     USA      M  55000.0   20
2    2    Jane Smith   NaN  Canada      F  62000.0   20
3    3          Alex   NaN     USA      M  47000.0   10
4    4  Maria Garcia  34.0   Spain      F      NaN   10
5    5        Li Wei  27.0   China      M  51000.0   20
6    6           NaN  45.0   India      F  73000.0   20
7    7    Ahmed Khan  38.0     NaN      M  68000.0   20
8    8    Rachel Lee  29.0     USA      F  62000.0   20
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0   10
10  10   Emily Davis  31.0     USA    NaN  58000.0   20

In [8]:
df = df.assign(new_income = df["income"] + df["income"]*df["tax"]/100)
df

    id          name   age country gender   income  tax  new_income
0    1      John Doe  29.0     USA      M  55000.0   20     66000.0
1    1      John Doe  29.0     USA      M  55000.0   20     66000.0
2    2    Jane Smith   NaN  Canada      F  62000.0   20     74400.0
3    3          Alex   NaN     USA      M  47000.0   10     51700.0
4    4  Maria Garcia  34.0   Spain      F      NaN   10         NaN
5    5        Li Wei  27.0   China      M  51000.0   20     61200.0
6    6           NaN  45.0   India      F  73000.0   20     87600.0
7    7    Ahmed Khan  38.0     NaN      M  68000.0   20     81600.0
8    8    Rachel Lee  29.0     USA      F  62000.0   20     74400.0
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0   10     49500.0
10  10   Emily Davis  31.0     USA    NaN  58000.0   20     69600.0

In [9]:
df.columns = [i.capitalize() for i in df.columns]
df

    Id          Name   Age Country Gender   Income  Tax  New_income
0    1      John Doe  29.0     USA      M  55000.0   20     66000.0
1    1      John Doe  29.0     USA      M  55000.0   20     66000.0
2    2    Jane Smith   NaN  Canada      F  62000.0   20     74400.0
3    3          Alex   NaN     USA      M  47000.0   10     51700.0
4    4  Maria Garcia  34.0   Spain      F      NaN   10         NaN
5    5        Li Wei  27.0   China      M  51000.0   20     61200.0
6    6           NaN  45.0   India      F  73000.0   20     87600.0
7    7    Ahmed Khan  38.0     NaN      M  68000.0   20     81600.0
8    8    Rachel Lee  29.0     USA      F  62000.0   20     74400.0
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0   10     49500.0
10  10   Emily Davis  31.0     USA    NaN  58000.0   20     69600.0

In [10]:
df.rename(columns={
    "Income":"Salary"
})
df

    Id          Name   Age Country Gender   Income  Tax  New_income
0    1      John Doe  29.0     USA      M  55000.0   20     66000.0
1    1      John Doe  29.0     USA      M  55000.0   20     66000.0
2    2    Jane Smith   NaN  Canada      F  62000.0   20     74400.0
3    3          Alex   NaN     USA      M  47000.0   10     51700.0
4    4  Maria Garcia  34.0   Spain      F      NaN   10         NaN
5    5        Li Wei  27.0   China      M  51000.0   20     61200.0
6    6           NaN  45.0   India      F  73000.0   20     87600.0
7    7    Ahmed Khan  38.0     NaN      M  68000.0   20     81600.0
8    8    Rachel Lee  29.0     USA      F  62000.0   20     74400.0
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0   10     49500.0
10  10   Emily Davis  31.0     USA    NaN  58000.0   20     69600.0

# Sorting

In [14]:
df.sort_values(["Income","Age","Name"])

    Id          Name   Age Country Gender   Income  Tax  New_income
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0   10     49500.0
3    3          Alex   NaN     USA      M  47000.0   10     51700.0
5    5        Li Wei  27.0   China      M  51000.0   20     61200.0
0    1      John Doe  29.0     USA      M  55000.0   20     66000.0
1    1      John Doe  29.0     USA      M  55000.0   20     66000.0
10  10   Emily Davis  31.0     USA    NaN  58000.0   20     69600.0
8    8    Rachel Lee  29.0     USA      F  62000.0   20     74400.0
2    2    Jane Smith   NaN  Canada      F  62000.0   20     74400.0
7    7    Ahmed Khan  38.0     NaN      M  68000.0   20     81600.0
6    6           NaN  45.0   India      F  73000.0   20     87600.0
4    4  Maria Garcia  34.0   Spain      F      NaN   10         NaN

In [15]:
df.reset_index()

    index  Id          Name   Age Country Gender   Income  Tax  New_income
0       0   1      John Doe  29.0     USA      M  55000.0   20     66000.0
1       1   1      John Doe  29.0     USA      M  55000.0   20     66000.0
2       2   2    Jane Smith   NaN  Canada      F  62000.0   20     74400.0
3       3   3          Alex   NaN     USA      M  47000.0   10     51700.0
4       4   4  Maria Garcia  34.0   Spain      F      NaN   10         NaN
5       5   5        Li Wei  27.0   China      M  51000.0   20     61200.0
6       6   6           NaN  45.0   India      F  73000.0   20     87600.0
7       7   7    Ahmed Khan  38.0     NaN      M  68000.0   20     81600.0
8       8   8    Rachel Lee  29.0     USA      F  62000.0   20     74400.0
9       9   9   Carlos Ruiz   NaN  Mexico      M  45000.0   10     49500.0
10     10  10   Emily Davis  31.0     USA    NaN  58000.0   20     69600.0

In [16]:
df.reset_index(drop=True)

    Id          Name   Age Country Gender   Income  Tax  New_income
0    1      John Doe  29.0     USA      M  55000.0   20     66000.0
1    1      John Doe  29.0     USA      M  55000.0   20     66000.0
2    2    Jane Smith   NaN  Canada      F  62000.0   20     74400.0
3    3          Alex   NaN     USA      M  47000.0   10     51700.0
4    4  Maria Garcia  34.0   Spain      F      NaN   10         NaN
5    5        Li Wei  27.0   China      M  51000.0   20     61200.0
6    6           NaN  45.0   India      F  73000.0   20     87600.0
7    7    Ahmed Khan  38.0     NaN      M  68000.0   20     81600.0
8    8    Rachel Lee  29.0     USA      F  62000.0   20     74400.0
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0   10     49500.0
10  10   Emily Davis  31.0     USA    NaN  58000.0   20     69600.0

In [18]:
sorted_df = df.sort_values(["Income","Age"]).copy()

sorted_df.reset_index(drop=True)

    Id          Name   Age Country Gender   Income  Tax  New_income
0    9   Carlos Ruiz   NaN  Mexico      M  45000.0   10     49500.0
1    3          Alex   NaN     USA      M  47000.0   10     51700.0
2    5        Li Wei  27.0   China      M  51000.0   20     61200.0
3    1      John Doe  29.0     USA      M  55000.0   20     66000.0
4    1      John Doe  29.0     USA      M  55000.0   20     66000.0
5   10   Emily Davis  31.0     USA    NaN  58000.0   20     69600.0
6    8    Rachel Lee  29.0     USA      F  62000.0   20     74400.0
7    2    Jane Smith   NaN  Canada      F  62000.0   20     74400.0
8    7    Ahmed Khan  38.0     NaN      M  68000.0   20     81600.0
9    6           NaN  45.0   India      F  73000.0   20     87600.0
10   4  Maria Garcia  34.0   Spain      F      NaN   10         NaN

In [19]:
sorted_df["Ranking"] = sorted_df["Income"].rank()

In [20]:
sorted_df

    Id          Name   Age Country Gender   Income  Tax  New_income  Ranking
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0   10     49500.0      1.0
3    3          Alex   NaN     USA      M  47000.0   10     51700.0      2.0
5    5        Li Wei  27.0   China      M  51000.0   20     61200.0      3.0
0    1      John Doe  29.0     USA      M  55000.0   20     66000.0      4.5
1    1      John Doe  29.0     USA      M  55000.0   20     66000.0      4.5
10  10   Emily Davis  31.0     USA    NaN  58000.0   20     69600.0      6.0
8    8    Rachel Lee  29.0     USA      F  62000.0   20     74400.0      7.5
2    2    Jane Smith   NaN  Canada      F  62000.0   20     74400.0      7.5
7    7    Ahmed Khan  38.0     NaN      M  68000.0   20     81600.0      9.0
6    6           NaN  45.0   India      F  73000.0   20     87600.0     10.0
4    4  Maria Garcia  34.0   Spain      F      NaN   10         NaN      NaN